# bunfig.toml

[install]
exact = true
concurrent = 10
cache = true
prefer-local = true

[install.scopes]
"@radix-ui" = { registry = "https://registry.npmjs.org/" }
"@vercel"   = { registry = "https://registry.npmjs.org/" }

[run]
bun = true
env = { NODE_ENV = "development" }

[test]
preload = ["./jest.setup.js"]

[dev]
hot = true
cmd = "next dev"
