name: Deploy to Vercel

on:
    push:
        branches: ["main"] # adjust if your production branch is different

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build project
              run: pnpm build

            - name: Deploy to Vercel
              run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
